/*
==============================================================================

This file was auto-generated by the Introjucer!

It contains the basic framework code for a JUCE plugin editor.

==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class ConvolutionReverbAudioProcessorEditor : public AudioProcessorEditor,
	Slider::Listener,
	ComboBox::Listener,
	Timer
{
public:
	ConvolutionReverbAudioProcessorEditor(ConvolutionReverbAudioProcessor&);
	~ConvolutionReverbAudioProcessorEditor();

	//==============================================================================
	void paint(Graphics&) override;

	void timerCallback()override;
	void sliderValueChanged(Slider* sliderThatWasChanged) override;
	void comboBoxChanged(ComboBox* comboBoxThatHasChanged) override;

private:
	// This reference is provided as a quick way for your editor to
	// access the processor object that created it.
	ConvolutionReverbAudioProcessor& processor;

	ScopedPointer<Slider> knob1;
	ScopedPointer<Slider> knob2;
	ScopedPointer<Slider> knob3;
	ScopedPointer<Slider> knob4;
	ScopedPointer<Slider> knob5;
	ScopedPointer<ComboBox> comboBox;
	JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(ConvolutionReverbAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
