/*
==============================================================================

This file was auto-generated by the Introjucer!

It contains the basic framework code for a JUCE plugin processor.

==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PreDelay.h"
#include "fftw3.h"
#include "FFTConvolver.h"
//==============================================================================
/**
*/
class ConvolutionReverbAudioProcessor : public AudioProcessor
{
public:
	//==============================================================================
	ConvolutionReverbAudioProcessor();
	~ConvolutionReverbAudioProcessor();

	//==============================================================================
	void prepareToPlay(double sampleRate, int samplesPerBlock) override;
	void releaseResources() override;

	void processBlock(AudioSampleBuffer&, MidiBuffer&) override;

	//==============================================================================
	AudioProcessorEditor* createEditor() override;
	bool hasEditor() const override;

	//==============================================================================
	const String getName() const override;

	int getNumParameters() override;
	float getParameter(int index) override;
	void setParameter(int index, float newValue) override;

	const String getParameterName(int index) override;
	const String getParameterText(int index) override;

	const String getInputChannelName(int channelIndex) const override;
	const String getOutputChannelName(int channelIndex) const override;
	bool isInputChannelStereoPair(int index) const override;
	bool isOutputChannelStereoPair(int index) const override;

	bool acceptsMidi() const override;
	bool producesMidi() const override;
	bool silenceInProducesSilenceOut() const override;
	double getTailLengthSeconds() const override;

	//==============================================================================
	int getNumPrograms() override;
	int getCurrentProgram() override;
	void setCurrentProgram(int index) override;
	const String getProgramName(int index) override;
	void changeProgramName(int index, const String& newName) override;

	//==============================================================================
	void getStateInformation(MemoryBlock& destData) override;
	void setStateInformation(const void* data, int sizeInBytes) override;
    void buttonClicked();
    void cmult(fftw_complex *c, fftw_complex *a, fftw_complex *b, int n);
    float setWetLevel(float m_fWetLevel, float m_fgain, float input);
    
	enum Parameters{
		knob1Param,
		knob2Param,
		knob3Param,
		knob4Param,
		knob5Param,
		totalNumParams
	};
    
    AudioSampleBuffer fileBuffer;

private:

	// raw Vars
	float m_knob1;
	float m_knob2;
	float m_knob3;
	float m_knob4;
	float m_knob5;

	float m_sampleRate;
	//cooked variables
	float m_fGain;
	float m_fDelayTime;
	float m_fFeedback;
	float m_fReverbTime;
	float m_fWetLevel;

    AudioFormatManager formatManager;
    int position;
	//for our interpolated delay time
	PreDelay PDelayL;
	PreDelay PDelayR;
    
    fftw_complex    *data, *impulse, *result;
    fftw_plan       pSig, pImp, pOut;
    
    int nfft ;
    float **olaBuffer ; // 2D overlap Add buffer
    float *filterSamples;
    float *dryBuffer ; // 1D circular buffer for LF
    float oldwet, wet;
    FFTConvolver *fft;
    
	//==============================================================================
	JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(ConvolutionReverbAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
